url: {{.Url}}
handler_template: shelly_25_relay_0
command_paths:
  power:
    power_on: /relay/0?turn=on
    power_off: /relay/0?turn=off
    power_toggle: /relay/0?turn=toggle
  status:
    path: /relay/0
