timeout: 1800
mqtt:
  listen_topics:
    - topic: fhem/{{.DeviceID}}/#
      handler_template: hm_thermostat
  command_topics:
    power:
      topic: fhem/cmnd
      payload_on: 'close'
      payload_off: 'open'
    temperature:
      topic: fhem/cmnd
      payload: 'set {{.DeviceID}} desired-temp %{temperature}.1f'
    status:
      topic: fhem/cmnd
      payload: list {{.DeviceID}} state