timeout: 60
optimistic: true
mqtt:
  listen_topics:
    - topic: shellies/{{.DeviceID}}/#
      handler_template: shelly_1
  command_topics:
    power:
      topic: shellies/{{.DeviceID}}/relay/0/command
      payload_on: 'on'
      payload_off: 'off'
      payload_toggle: 'toggle'
    status:
      topic: shellies/{{.DeviceID}}/relay/0
      payload: ''
rest:
  url: {{.Url}}
  handler_template: shelly_1
  command_paths:
    power:
      power_on: /relay/0?turn=on
      power_off: /relay/0?turn=off
      power_toggle: /relay/0?turn=toggle
    status:
      path: /relay/0
