timeout: 60
optimistic: true
mqtt:
  listen_topics:
    - topic: shellies/{{.DeviceID}}/#
      handler_template: shelly_25_roller
  command_topics:
    power:
      topic: shellies/{{.DeviceID}}/roller/0/command
      payload_on: 'close'
      payload_off: 'open'
      payload_toggle: 'toggle'
    position:
      topic: shellies/{{.DeviceID}}/roller/0/command/pos
      payload: '%{position}.0f'
    status:
      topic: shellies/{{.DeviceID}}/roller/0
      payload: ''
    pause:
      topic: shellies/{{.DeviceID}}/roller/0/command
      payload: 'stop'
rest:
  url: {{.Url}}
  handler_template: shelly_25_roller
  command_paths:
    power:
      power_on: '/roller/0?go=close&duration=0'
      power_off: '/roller/0?go=open&duration=0'
    status:
      path: /status
    position:
      path: '/roller/0?go=to_pos&roller_pos=%{position}.0f'
    pause:
      path: '/roller/0?go=stop&duration=0'
supplemental:
  - field: 'temperature'
    caption: 'Temperatur'
    format: '%.1f'
