timeout: -1
mqtt:
  listen_topics:
    - topic: z2m/{{.DeviceID}}
      handler_template: snzb02
supplemental:
  - field: 'temperature'
    caption: 'Temperatur'
    format: '%.1f'
  - field: 'humidity'
    caption: 'Feuchtigkeit'
    format: '%.1f'
  - field: 'battery'
    caption: 'Batterie'
    format: '%.1f'
  - field: 'voltage'
    caption: 'Voltage'
    format: '%.1f'
