optimistic: true
timeout: 60
mqtt:
  listen_topics:
    - topic: tele/{{.DeviceID}}/#
      handler_template: tasmota_tele
    - topic: stat/{{.DeviceID}}/#
      handler_template: tasmota_stat
  command_topics:
    power:
      topic: cmnd/{{.DeviceID}}/Power
      payload_on: 'on'
      payload_off: 'off'
      payload_toggle: 'toggle'
    status:
      topic: cmnd/{{.DeviceID}}/Power
      payload: ''
rest:
  url: {{.Url}}
  handler_template: tasmota
  command_paths:
    power:
      power_on: '/cm?cmnd=Power On'
      power_off: '/cm?cmnd=Power Off'
      power_toggle: '/cm?cmnd=Power Toggle'
    status:
      path: '/cm?cmnd=Status 0'