listen_topics:
  - topic: z2m/{{.DeviceID}}
    handler_template: hg06337
command_topics:
  power:
    topic: z2m/{{.DeviceID}}/set
    payload_on: '{"state": "on"}'
    payload_off: '{"state": "off"}'
    payload_toggle: '{"state": "toggle"}'
  status:
    topic: cmnd/{{.DeviceID}}/get
    payload: '{"state":""}'
