listen_topics:
  - topic: shellies/{{.DeviceID}}/#
    handler_template: shelly_25_relay_0
command_topics:
  power:
    topic: shellies/{{.DeviceID}}/relay/0/command
    payload_on: 'on'
    payload_off: 'off'
    payload_toggle: 'toggle'
  status:
    topic: shellies/{{.DeviceID}}/relay/0
    payload: ''
