listen_topics:
  - topic: tele/{{.DeviceID}}/#
    handler_template: tasmota_tele
  - topic: stat/{{.DeviceID}}/#
    handler_template: tasmota_stat
command_topics:
  power:
    topic: cmnd/{{.DeviceID}}/Power
    payload_on: 'on'
    payload_off: 'off'
    payload_toggle: 'toggle'
  status:
    topic: cmnd/{{.DeviceID}}/Power
    payload: ''

